# Generated by Django 4.2.1 on 2024-04-10 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
